#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

die () {
    echo "$*" >&2
    exit 1
}

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || exit

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    fi
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ] ; then
    die "ERROR: gradle-wrapper.jar not found. Open this project in Android Studio so the IDE can generate the Gradle Wrapper, or run: gradle wrapper --gradle-version 8.9"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
